fix every function's $result variable
lilmayofuksu/php-rcon-xash pull request #1
Opened 2022-02-13 23:19 UTC by bariscodefxy

2022-02-13 23:26 UTC, lilmayofuksu requested changes

2022-02-13 23:26 UTC, lilmayofuksu commented on phprcon.php
> +                                $result = [];
this should be tabs, not spaces.

2022-02-13 23:26 UTC, lilmayofuksu commented on phprcon.php
> +                                $result = [];
this too

2022-02-14 04:07 UTC, bariscodefxy commented
because i did it on my phone. I will do again on my pc.

2022-02-14 17:19 UTC, merged